name: ringdown
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - h5py
  - arviz
  - matplotlib
  - pandas
  - scipy
  - lalsuite
  - qnm
  - seaborn
  - python=3
  - jupyterlab
  - ipywidgets
  - openblas
  - numpyro
  - jax
  - jaxlib
